POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZyZWRBbGxleSIsImlkIjoiNjBjYTY5YTE4OTYyZTBhZDY2ZDFjMDhmIiwiaWF0IjoxNjIzODkxMjU0fQ.ps-ZTGgQZRTl-AYwiLC4ZGTe6F3tP2Rw-wSzJJs_3ZI

{
    "title": "testTitleFred",
    "author": "Fred Alley",
    "url": "http://testURL",
    "likes": 7
}